#! /bin/bash
#Author: PratibhaMastud

a=o
sum=0

while(true)
do
	firstDice=$((RANDOM%6+1))
	secondDice=$((RANDOM%6+1))

	if [ $firstDice -eq 6 -a $secondDice -eq 6 ]
	then
		break
	elif [ $firstDice -lt 6 -a $secondDice -lt 6 ]
	then
		totalRolls=$(($a + 1))
		sum=$(($sum + $firstDice + $secondDice ))
	fi
done
echo "The Number of rolles : $totalRolls"
echo "The Sum of rolls : $sum"
